# Generated by Django 2.2.7 on 2020-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='S', max_length=1)),
                ('type', models.CharField(default='Margarita', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('delivered', models.CharField(choices=[('order_getted', 'ORDER GETTED'), ('preparing', 'PREPARING'), ('at_courier', 'AT COURIER'), ('delivered', 'DELIVERED')], default='order_getted', max_length=50)),
                ('customer', models.ManyToManyField(to='api.Customers')),
                ('pizza', models.ManyToManyField(to='api.Pizzas')),
            ],
        ),
    ]
