# Generated by Django 2.2.7 on 2019-11-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191116_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('preparing', 'PREPARING'), ('at_courier', 'AT COURIER'), ('delivered', 'DELIVERED')], default='preparing', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
