# Generated by Django 2.2.7 on 2019-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191117_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('order_getted', 'ORDER GETTED'), ('preparing', 'PREPARING'), ('at_courier', 'AT COURIER'), ('delivered', 'DELIVERED')], default='order_getted', max_length=50),
        ),
    ]
