# Generated by Django 2.2.7 on 2019-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
